 
name: Node.js CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Check frontend changes
      run: |
        git diff-tree --name-only HEAD | grep webapp-admin
        $? || exit 1
    - name: Build frontend
      run: |
        cd webapp-admin
        npm install
        npm run build
        cp -R build/static/js ../static
        cp -R build/static/css ../static
        cp -R build/index.html ../static/app.html
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Added js/css files
        title: 'Automated javascript build'
