name: Node.js CI

on:
  push:
    branches: master
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js lts/*
      uses: actions/setup-node@v1
      with:
        node-version: lts/*
    - run: |
        cd webapp-admin
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
